### ISSUE TITLE
Couldn't correct orientation: java.lang.IllegalStateException error when trying to do UnSharpMasking

### ISSUE THREAD

**Issue by sunnybirman** [DiegoCatalano/Catalano-Framework#16]
I am processing an Image to make it Tesseract-OCR friendly using Catalano framework. Thresholding is working fine but when I try to UnsharpMasking or resizing I get an error Couldn't correct orientation: java.lang.IllegalStateException: Can't call setPixels() on a recycled bitmap even though I have set BitmapFactory options inmutable to true & minsdk=11.

Code snippet:
            FastBitmap fb = new FastBitmap(bitmap);
            Grayscale grayScale = new Grayscale();
            grayScale.applyInPlace(fb);

            switch (thresholdFilterName) {
            case "Threshold":  Threshold t = new Threshold(100);
            t.applyInPlace(fb);
            break;

            case "BradleyLocalThreshold":  BradleyLocalThreshold blt = new BradleyLocalThreshold();
            blt.applyInPlace(fb);
            break;

            case "SauvolaThreshold":  SauvolaThreshold st =new SauvolaThreshold();
            st.applyInPlace(fb);
            break;

            case "NiblackThreshold":  NiblackThreshold nt =new NiblackThreshold();
            nt.applyInPlace(fb);
            break;

            case "WolfJoulionThreshold": WolfJoulionThreshold wjt =new WolfJoulionThreshold();
            wjt.applyInPlace(fb);
            break;

            default: WolfJoulionThreshold wjtD =new WolfJoulionThreshold();
            wjtD.applyInPlace(fb);
            break;

            }

            UnsharpMasking um= new UnsharpMasking();
            um.applyInPlace(fb);
        // exception is thrown here.

Another thing is that BradleyLocalThreshold gives best result in lighting conditions where there is shadow on image but the accuracy of OCR engine is poor with it, where as accuracy with HysteresisThreshold is quiet high but it doesn't work well in lighting conditions. Is there any way we have best of both algorithms.

**Comment by DiegoCatalano** [comment]
Hello Sunnybirman,

Just comment the line [127](https://github.com/DiegoCatalano/Catalano-Framework/blob/master/Catalano.Android.Image/src/Catalano/Imaging/Filters/UnsharpMasking.java#L127) in the class UnsharpMasking, this occurs because I forget to remove this line. I'll fix today yet.

In near future, I'll write [phase congruency](http://www.csse.uwa.edu.au/~pk/Research/research.html), a method of edge detection that is particularly robust against changes in illumination and contrast. Maybe this filter can help you. In the case, if you send me the images, I can try to help you too.

Cheers !!

**Comment by DiegoCatalano** [comment]
Fixed now.

**Comment by sunnybirman** [comment]
![img_20150710_104541](https://cloud.githubusercontent.com/assets/8857494/8612629/2808f648-26f1-11e5-8260-ef62af7e27e7.jpg)
This is the Image of business card that I am working on.There is uneven lightning condition here.

Thanks

**Comment by DiegoCatalano** [comment]
Hello Sunnybirman,

I got the results following this code:

```java
        Grayscale g = new Grayscale();
        g.applyInPlace(fb);
        
        Resize r = new Resize(fb.getWidth() / 3, fb.getHeight() / 3);
        r.applyInPlace(fb);
        
        Clahe c = new Clahe(65,127,3);
        c.applyInPlace(fb);
        
        BradleyLocalThreshold b = new BradleyLocalThreshold();
        b.applyInPlace(fb);
        
        Invert i = new Invert();
        i.applyInPlace(fb);
        
        BlobsFiltering bf = new BlobsFiltering(0,100);
        bf.applyInPlace(fb);
```

![sunny](https://cloud.githubusercontent.com/assets/5301914/8624418/1773e032-270e-11e5-9522-352500b96647.png)

Cheers !!!
