### ISSUE TITLE
Instagram like Filters

### ISSUE THREAD

**Issue by deepinder10** [DiegoCatalano/Catalano-Framework#17]
Hi, I really like your work on image processing.
It would be great if you can add the filters same to those in Instagram (Amaro,Lomo-fi,etc)
It would be a great help.
thanks

**Comment by DiegoCatalano** [comment]
Hello Deepinder Singh,

A lot of filters of instagram uses curves levels adjustments. I'll write in the framework and some filters like instagram in the Artistic namespaces.

Cheers.!

**Comment by deepinder10** [comment]
Hoping to see that soon.
Thanks a lot Diego.

**Comment by DiegoCatalano** [comment]
Hi Deepinder Singh,

[Levels Curve](https://github.com/DiegoCatalano/Catalano-Framework/blob/master/Catalano.Image/src/Catalano/Imaging/Filters/LevelsCurve.java) is ready.
