### ISSUE TITLE
Can you show the screenshots of the filters?

### ISSUE THREAD

**Issue by deepinder10** [DiegoCatalano/Catalano-Framework#18]
Hi Catalano,you have a lot of filters available in your library that i am really confused which one to use,can you put up images of every filter taking a single photo and applying every one on that so that everyone can easily get to know what each filter does to my photo.It would be a great help.
And please add the vignette effect if possible.
Thanks

**Comment by DiegoCatalano** [comment]
Hello Deepinder Singh,
Can you give me another email ?, I tried with no sucess to send an example to you. I tried this email: sdeepinder8@gmail.com

**Comment by deepinder10** [comment]
actually the email is correct, please try sdeepinder10@gmail.com or deepinder10@hotmail.com.

I am building a effects applciation and i tried jhlabs which is reallly slow in loading and yours is perfect and i am eagerly waiting for instagram filters as i want to implment them.Please keep that on high priority if possible 
https://www.quora.com/How-does-Instagram-develop-their-filters
this may help you but the project is not available due to dmca takedown.
Thanks

**Comment by DiegoCatalano** [comment]
Hello Deepinder Singh,

I'm finishing the article where I describe how filters learn from the results of others, so it will be missing the vignette. ;)

Give me more +- 3 days.

**Comment by deepinder10** [comment]
Hi Diego,
Any progress on the Instagram Filters.?
And i didn't get the examples of the filters, can you please try to send it again,it would be very helpful.
Thanks

**Comment by DiegoCatalano** [comment]
Hello Deepinder Singh,

You can follow this [tutorial](http://www.instructables.com/id/How-to-make-Instagram-Filters-in-Photoshop/).

Attention: Read the [license](http://creativecommons.org/licenses/by-nc-sa/2.5/) to follow the article.

Let's create a custom Lomo filter following this lomo function below.

![mycurves](https://cloud.githubusercontent.com/assets/5301914/10766257/ceb62b6a-7cbd-11e5-80aa-cce9876b4b35.png)

        //Lomo-fi curves.
        FastBitmap fb = new FastBitmap("flower.jpg");
        
        Curve red = new Curve();
        red.addPoint(53/255f, 38/255f);
        red.addPoint(99/255f, 110/255f);
        red.addPoint(158/255f, 194/255f);
        red.addPoint(195/255f, 221/255f);
        
        Curve green = new Curve();
        green.addPoint(63/255f, 40/255f);
        green.addPoint(123/255f, 122/255f);
        green.addPoint(167/255f, 198/255f);
        green.addPoint(206/255f, 229/255f);
        
        Curve blue = new Curve();
        blue.addPoint(84/255f, 66/255f);
        blue.addPoint(129/255f, 131/255f);
        blue.addPoint(153/255f, 193/255f);
        blue.addPoint(201/255f, 230/255f);
        
        LevelsCurve l = new LevelsCurve(red, green, blue);
        l.applyInPlace(fb);
        
        JOptionPane.showMessageDialog(null, fb.toIcon());

Now the results:

Original

![flower2](https://cloud.githubusercontent.com/assets/5301914/10766545/34c759a0-7cbf-11e5-9f6b-be65513e400a.jpg)

Lomo filter

![flower2lf](https://cloud.githubusercontent.com/assets/5301914/10766551/39136e2c-7cbf-11e5-8b71-57ba7b51e0be.jpg)

**Comment by deepinder10** [comment]
Hi Diego,
i tried the amaro filter from the link you gave but the result went worse.
Here is the code

FastBitmap fb = new FastBitmap(mOrigBitmap);

        Curve red = new Curve();
        red.addPoint(0/255f, 19/255f);
        red.addPoint(30/255f, 62/255f);
        red.addPoint(82/255f, 148/255f);
        red.addPoint(128/255f, 88/255f);
        red.addPoint(145/255f, 200/255f);
        red.addPoint(255/255f, 250/255f);

        Curve green = new Curve();
        green.addPoint(0/255f, 0/255f);
        green.addPoint(48/255f, 72/255f);
        green.addPoint(115/255f, 188/255f);
        green.addPoint(160/255f, 120/255f);
        green.addPoint(233/255f, 245/255f);
        green.addPoint(255/255f, 255/255f);

        Curve blue = new Curve();
        blue.addPoint(0/255f, 25/255f);
        blue.addPoint(35/255f, 80/255f);
        blue.addPoint(106/255f, 75/255f);
        blue.addPoint(151/255f, 188/255f);
        blue.addPoint(215/255f, 215/255f);
        blue.addPoint(240/255f, 235/255f);
        blue.addPoint(255/255f, 245/255f);

        LevelsCurve l = new LevelsCurve(red, green, blue);
        l.applyInPlace(fb);
        return fb.toBitmap();


![img_20151029133113 1](https://cloud.githubusercontent.com/assets/13166004/10813071/1fc4b94c-7e42-11e5-9858-2df31577f208.jpg)
![img_20151029133323 1](https://cloud.githubusercontent.com/assets/13166004/10813074/2987d464-7e42-11e5-9de6-7ccb9d6081d7.jpg)

Can you please show me a demo from the link you gave me integrated with your curve.

**Comment by DiegoCatalano** [comment]
There is a little problem in the method addPoint, I'll fix today in few hours.

**Comment by deepinder10** [comment]
So, i need to download new jar file for your library after you fix that.?

**Comment by DiegoCatalano** [comment]
The curve isn't wrong, there is something strange in the tutorial, anyway you can use the values below, I take the values in this [project](https://github.com/mordonez-me/instagram-filters-jhlabs-android):

        Curve red = new Curve();
        red.addPoint(0/255f, 26/255f);
        red.addPoint(15/255f, 43/255f);
        red.addPoint(32/255f, 64/255f);
        red.addPoint(65/255f, 114/255f);
        red.addPoint(83/255f, 148/255f);
        red.addPoint(109/255f, 177/255f);
        red.addPoint(127/255f, 193/255f);
        red.addPoint(146/255f, 202/255f);
        red.addPoint(170/255f, 208/255f);
        red.addPoint(195/255f, 218/255f);
        red.addPoint(215/255f, 229/255f);
        red.addPoint(234/255f, 241/255f);
        red.addPoint(255/255f, 251/255f);
        
        Curve green = new Curve();
        green.addPoint(0/255f, 0/255f);
        green.addPoint(26/255f, 32/255f);
        green.addPoint(49/255f, 72/255f);
        green.addPoint(72/255f, 123/255f);
        green.addPoint(89/255f, 147/255f);
        green.addPoint(115/255f, 188/255f);
        green.addPoint(147/255f, 205/255f);
        green.addPoint(160/255f, 210/255f);
        green.addPoint(177/255f, 222/255f);
        green.addPoint(189/255f, 224/255f);
        green.addPoint(215/255f, 235/255f);
        green.addPoint(234/255f, 246/255f);
        green.addPoint(255/255f, 255/255f);
        
        Curve blue = new Curve();
        blue.addPoint(1/255f, 29/255f);
        blue.addPoint(30/255f, 72/255f);
        blue.addPoint(57/255f, 124/255f);
        blue.addPoint(74/255f, 147/255f);
        blue.addPoint(87/255f, 162/255f);
        blue.addPoint(108/255f, 175/255f);
        blue.addPoint(130/255f, 184/255f);
        blue.addPoint(152/255f, 189/255f);
        blue.addPoint(172/255f, 195/255f);
        blue.addPoint(187/255f, 203/255f);
        blue.addPoint(215/255f, 216/255f);
        blue.addPoint(239/255f, 237/255f);
        blue.addPoint(255/255f, 247/255f);

I got the results below:

![store2](https://cloud.githubusercontent.com/assets/5301914/10833712/2f908b74-7e7b-11e5-9c8a-13da28249af8.jpg)

**Comment by DiegoCatalano** [comment]
There is another tutorial [here](http://www.howtogeek.com/68431/create-instagram-style-photo-effects-with-gimp-or-photoshop/). You can apply in the framework as well. See the code below and the result:

        FastBitmap fb = new FastBitmap("image.jpg");
        FastBitmap layer = new FastBitmap(fb.getWidth(), fb.getHeight());
        
        int size = layer.getSize();
        for (int i = 0; i < size; i++) {
            layer.setRGB(i, 250, 220, 175);
        }
        
        IntRange green = new IntRange(33, 255);
        IntRange blue = new IntRange(143, 255);
        IntRange rgb = new IntRange(37, 239);
        
        LevelsLinear levels = new LevelsLinear();
        levels.setOutGreen(green);
        levels.setOutBlue(blue);
        
        levels.setInGreen(rgb);
        levels.setInGreen(rgb);
        levels.setInBlue(rgb);
        
        levels.applyInPlace(fb);
        
        Blend blend = new Blend(layer, Blend.Algorithm.Multiply);
        blend.applyInPlace(fb);
        
        JOptionPane.showMessageDialog(null, fb.toIcon());

The result:

![store3](https://cloud.githubusercontent.com/assets/5301914/10834415/55375060-7e80-11e5-89c8-4f129cde828b.jpg)
