### ISSUE TITLE
FakeHDR: Can't call setPixels() on a recycled bitmap

### ISSUE THREAD

**Issue by lionelmessi** [DiegoCatalano/Catalano-Framework#24]
Hi Diego,

I am trying to use the FAKE HDR in Android but I get this error on using it. Can you help in providing pointers as to where to look.

Thanks!

**Comment by lionelmessi** [comment]
I have a grayscale image and would like to enhance the quality in terms of brightness and contrast (Somewhere on the lines of Matlab: imadjust, adapthisteq). The original images appear to be washed out.

Which function would you like to suggest for this kind of problem? I also looked at AdaptiveContrastEnhancement() but not able to figure out good values for the contants! Any help is highly appreciated.

**Comment by DiegoCatalano** [comment]
Hello lionelmessi,

The FakeHDR is fixed.
To achieve the results of imadjust, you can use [HistogramAdjust](https://github.com/DiegoCatalano/Catalano-Framework/blob/master/Catalano.Android.Image/src/Catalano/Imaging/Filters/HistogramAdjust.java) (works in RGB too :)).
You can try others filters as: Clahe, HistogramEqualization, HistogramStretch.

Cheers !

**Comment by lionelmessi** [comment]
Ohh great! BTW I wrote that myself yesterday but pulled and compared with you. Works awesome!
