### ISSUE TITLE
Threshold not working when inverted

### ISSUE THREAD

**Issue by Nopalin** [DiegoCatalano/Catalano-Framework#26]
I found a bug in the threshold class, when it is not inverted a value greather or equals than the specified is white, but when it is inverted a value less than the specified is black, painting in both cases the same images. Just need to change the condicional from less than to greather or equals to.

Greetings

**Comment by DiegoCatalano** [comment]
Hello Nopalin,

This class is so old. I have reworked now and this bug is fixed. Much thanks !

Cheers !
