### ISSUE TITLE
For Jar Request

### ISSUE THREAD

**Issue by GowthamanRajasekaran** [DiegoCatalano/Catalano-Framework#36]
Hi DiegoCatalano, 

                     I am now trying to use your updated Catalano-Framework for android image processing, I am getting issues of some missing sub files. Can you provide Jar Files or Gradle for Core,Fuzzy,Math and other libraries.

**Comment by amirdaraei** [comment]
Hi everybody
I have the same problem as GowthamanRajasekaran said, when I used the library image or image android in android studio IDE give me an error about missing some class library like ImageUtil and when I added manually give the error about MaxMin plz help us.

**Comment by DiegoCatalano** [comment]
Hello,

I'll create a new release with updated jars asap.

Cheers !!!

**Comment by GowthamanRajasekaran** [comment]
Thank you @DiegoCatalano , Actually the Package  Library of Core, Math,Statistics are starting wit UpperCase letters. While running the code, android gives error 

> _install_parse_failed_manifest_malformed_ in android studio.
To solve this, i changed each and every file into Lowercase letters, now problem is solved and working properly.

**Comment by Tosken1337** [comment]
Also would like to have a new release.
Thanks ;)

**Comment by nickaein-a** [comment]
waiting for new release ...

**Comment by DiegoCatalano** [comment]
Hello everybody,

I'm preparing now, the eta is about 1 hour.

**Comment by DiegoCatalano** [comment]
Hi @GowthamanRajasekaran,

I'm currently using Android Studio 2.2.3. The upper case letters doesn't give errors. Can you send me a print screen plz ?

Thanks

**Comment by GowthamanRajasekaran** [comment]
Hi @DiegoCatalano ,

       As for your reference, i attached the print screen error which i got while using as the library. I am also using Android Studio 2.2.3 only.

![image](https://cloud.githubusercontent.com/assets/24268504/21795521/7157108a-d728-11e6-81c3-e9acbac274f5.png)

Thanks

**Comment by amirdaraei** [comment]
Hi @GowthamanRajasekaran 
Change name package with Caps letters to little letters.

**Comment by GowthamanRajasekaran** [comment]
Hi @amirdaraei , 

        when i change package name, the internal library files also needs to be changed. After changing package and internal files, now it is working.

**Comment by amirdaraei** [comment]
Hi guys
there is a problem:
I use OpenCV for detect eyes in my project and I intend to use Catalano library for use MultiScaleRetinex(for illumination enhancement) but there is a problem when I passed camera frame to the library, the library just accepted bitmap parameters and I don't know what to do...
Any help will be appreciated 
PS: attached screen shot
![Uploading Untitled.jpg…]()

**Comment by GowthamanRajasekaran** [comment]
Hi @DiegoCatalano ,

            Thank you for releasing Jar Files, this helps me to process easily .
