### ISSUE TITLE
Problem with SingleScaleRetinex

### ISSUE THREAD

**Issue by amirdaraei** [DiegoCatalano/Catalano-Framework#38]
Hi,@DiegoCatalano 
thanks a lot and appreciate you for the useful library but have you ever tested SingleScaleRetinex and other samples like MultiScaleRetinex  ???

**Comment by DiegoCatalano** [comment]
Hello, @amirdaraei,

For some reason im computing the log with negative values, this is wrong, its generating black images, I'll fix this.

Thank you

**Comment by DiegoCatalano** [comment]
Fixed.

@amirdaraei If you find any problem you can contact. It will be a pleasure to help you.

**Comment by amirdaraei** [comment]
Thanks for your attention, I have problem with:   
        //Transform the image in matrix.
        double[][] image = fastBitmap.toMatrixGrayAsDouble();
  it doesn't recognize "toMatrixGrayAsDouble()" method 
and I can't import ImageUtil from the library?
PS:I have worked in Android Studio Library and I intend to use Retinex method for Camera frame
I'll appreciate it if you give me your e-mail.

**Comment by DiegoCatalano** [comment]
This is strage.

This is my email: diego.catalano@live.com
