### ISSUE TITLE
Android: Concurrent HSLFilter bug?!

### ISSUE THREAD

**Issue by tarrew** [DiegoCatalano/Catalano-Framework#42]
Hey, 

i tried using the concurrent HSLFilter in an Android application. It didn't work at all, so i tried debugging the app:
![hslfilter](https://cloud.githubusercontent.com/assets/9460805/23459654/9cb28842-fe81-11e6-81a5-c53e4bceb32b.PNG)

Previously the Share-Object is created like this [here](https://github.com/DiegoCatalano/Catalano-Framework/blob/master/Catalano.Image/src/Catalano/Imaging/Concurrent/Filters/HSLFiltering.java#L225): 
`t[i] = new Thread(new Run(new Share(fastBitmap, startX, startX + part)));`

Since the Share object is initialized without the endWidth parameter, it is 0, which will cause the algorithm to never execute the inner for-loop. 

Hope this can be fixed in the next release.

**Comment by DiegoCatalano** [comment]
Hello tarrew,

I had forgotten to set the "endWidth" parameter in the Share class.
It's already [fixed](https://github.com/DiegoCatalano/Catalano-Framework/commit/9865ec312bf3e0c1006646711cedb48571df9a37).

Thank you so much 👍
