### ISSUE TITLE
How can I increase the DPI of an image?

### ISSUE THREAD

**Issue by ksmallik** [DiegoCatalano/Catalano-Framework#45]
Hi Folks,
   This is one of the most useful image processing libraries for Android. And what for bytes (lean and mean). Presently I need to increase the dpi(resolution) of an image. Should I use ResizeBicubic?

**Comment by DiegoCatalano** [comment]
Hello @ksmallik,

DPI is different than resolution. [[Source](https://www.vsellis.com/understanding-dpi-resolution-and-print-vs-web-images/)]

DPI: Dot’s per inch. The number of dots in a printed inch. The more dot’s the higher the quality of the print (more sharpness and detail).

Resolution: Resolution is the measure of pixels in the display, usually expressed in measurements of width x height.

For increase the resolution, you can apply resize algorithms (Bicubic, Bilinear, Nearest Neighbor). Actually, in that library, the bicubic is better.

For increase the DPI you can call the method: saveAsJPG(image, quality, xDpi, yDpi). This method only supports desktop, I'll port to android if you desire.

Look the image below, has the same resolution but with dpi differents.

![image](https://user-images.githubusercontent.com/5301914/27520460-988183ec-59e2-11e7-82d2-4944f416a247.png)

**Comment by ksmallik** [comment]
Thanks for the reply @Diego. Thanks for the clarification. Yes, please port the method saveAsPNG() and saveAsXXX() methods. They would be very useful. When can we expect it?

**Comment by ksmallik** [comment]
@DiegoCatalano, can you atleast provide the java code for saveAsPNG() for Android. Need it for my app.

**Comment by ksmallik** [comment]
Thanks @DiegoCatalano. Just saw your added support function. How do I compile your code into a jar?

**Comment by ksmallik** [comment]
@DiegoCatalano I see that the DPI support is in Imaging Library(Have you ported to Android yet?).

**Comment by DiegoCatalano** [comment]
@ksmallik, I'm sorry, I was away solving a problem in the dissertation.

I'll port to android now

**Comment by ksmallik** [comment]
@DiegoCatalano Can you make it saveAsPNG()?

**Comment by ksmallik** [comment]
@DiegoCatalano I don't see the android port? I understand that you have your dissertation, but please try to port the method today. Thanks.

**Comment by ksmallik** [comment]
@DiegoCatalano I will setttle for saveAsJPG(). Thanks.

**Comment by ksmallik** [comment]
Such a wonderful library and all I asked was one method to be added to it. I am very dissappointed @DiegoCatalano

**Comment by SakuKaukonen** [comment]
@ksmallik 

Diego has been doing excellent work with this library and I personally appreciate his work a lot! 

Remember that developers rarely have the possibility to work all of his/her time on a single open source project. It is a bit naive to expect that requests (no matter how small or big) are immediately handled by the developer (or within days or even weeks). I bet Diego has some other duties in his life as well. 

However, I'm sure he will implement your request (and all other requests in the pipeline) as soon as he can.

So, please, have patience and let the man do his work as he chooses.

**Comment by ksmallik** [comment]
@SakuKaukonen I apologize. As I mentioned in the first post, this is one of the rising frameworks. Maybe I expected him to provide a solution as soon as he said.  I am new to asking for feature requests from the owner. Yes let him work at his pace and time.

**Comment by DiegoCatalano** [comment]
@ksmallik ,

I apologize a lot, this weekend including until yesterday I was not programming anything because I was traveling to hold some contests, I did not really have any time, but today I came back focused on helping you.

Today I will create the saveAsPNG () method, I promise.

**Comment by DiegoCatalano** [comment]
The saveAsJPG() and saveAsPNG() is ready, I'm going to commit in an hour at the most.

**Comment by DiegoCatalano** [comment]
@ksmallik,

The [saveAsJPG()](https://github.com/DiegoCatalano/Catalano-Framework/blob/master/Catalano.Android.Image/src/Catalano/Imaging/FastBitmap.java#L992) and [saveAsPNG()](https://github.com/DiegoCatalano/Catalano-Framework/blob/master/Catalano.Android.Image/src/Catalano/Imaging/FastBitmap.java#L1043) is ready, both support DPI in X and Y axis.

I'm sorry for the delay, until August I will be delaying to make new updates because I need to finish the master's degree.

Cheers !

**Comment by ksmallik** [comment]
You rock @DiegoCatalano!!
