### ISSUE TITLE
Gaussian 2D equation which one to choose ?

### ISSUE THREAD

**Issue by vincent-roth** [DiegoCatalano/Catalano-Framework#50]
Hi,
A question about gaussian.java
The equation of Function2D is written :
`Math.exp(-(x * x + y * y) / (2 * sqrSigma))
`
But according to [wikipedia](https://en.wikipedia.org/wiki/Gaussian_blur)
Shouldn't it be: 
`Math.exp(-(x * x + y * y) / (2 * sqrSigma))/(2*Math.PI*sqrSigma)
`

Thank you for the framework, Vincent

**Comment by DiegoCatalano** [comment]
Hello @vincent-roth,

I forget to fix the 2D. Thank you !
