### ISSUE TITLE
Perspective transformation

### ISSUE THREAD

**Issue by SivaramSS** [DiegoCatalano/Catalano-Framework#58]
Hi,

Can someone tell me how to perform perspective transformation using this framework?

Please refer the images in this thread regarding perspective transformation
http://answers.opencv.org/question/102464/android-opencv-perspective-transformation-not-working-as-expected/

**Comment by DiegoCatalano** [comment]
Hello, @SivaramSS 

I took this picture from the internet as an example.

![quad](https://user-images.githubusercontent.com/5301914/52097149-c3be2100-25b0-11e9-8e30-7b6cad59fa22.png)

Just run the code below

        FastBitmap fb = new FastBitmap("c:\\files\\quad.png");
        
        List<IntPoint> lst = new ArrayList<>(4);
        lst.add(new IntPoint(174,48)); //A coordinate
        lst.add(new IntPoint(79,265)); //B coordinate
        lst.add(new IntPoint(189,356)); //C coordinate
        lst.add(new IntPoint(327,136)); //D coordinate
        
        QuadrilateralTransformation qt = new QuadrilateralTransformation(lst);
        fb = qt.ProcessImage(fb);

![image](https://user-images.githubusercontent.com/5301914/52097206-1566ab80-25b1-11e9-83d0-cd8aaa5907a9.png)

If you find a problem, can you let me know

Cheers !

**Comment by DiegoCatalano** [comment]
Please, use the new version [1.6.1](https://github.com/DiegoCatalano/Catalano-Framework/releases/download/v1.6.1-libs/libs.zip)

**Comment by SivaramSS** [comment]
Hi Diego,
IntPoint is not available in Android. I'm not able to run this code.
